package com.myspace.cib_phase2.modal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Amount")
	private java.lang.Long amount;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label(value = "Group Info")
	private java.util.Set<com.myspace.cib_phase2.modal.CIBGroupInfo> cibGroupInfo;

	public Transaction() {
	}

	public java.lang.Long getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Long amount) {
		this.amount = amount;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public String toString() {
		return "amount: " + amount + " status: " + status + " userGroup: "
				+ cibGroupInfo;
	}

	public java.util.Set<com.myspace.cib_phase2.modal.CIBGroupInfo> getCibGroupInfo() {
		return this.cibGroupInfo;
	}

	public void setCibGroupInfo(
			java.util.Set<com.myspace.cib_phase2.modal.CIBGroupInfo> cibGroupInfo) {
		this.cibGroupInfo = cibGroupInfo;
	}
	
	public void addUsergroups(com.myspace.cib_phase2.modal.CIBGroupInfo cibGroupInfo) {
    	if(this.cibGroupInfo == null) {
	        this.cibGroupInfo = new java.util.HashSet();
	      }
	this.cibGroupInfo.add(cibGroupInfo);
	}

	public Transaction(
			java.lang.Long amount,
			java.lang.String status,
			java.util.Set<com.myspace.cib_phase2.modal.CIBGroupInfo> cibGroupInfo) {
		this.amount = amount;
		this.status = status;
		this.cibGroupInfo = cibGroupInfo;
	}

}