package com.myspace.cib_phase2.modal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CIBGroupInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Affirmation Count")
	private java.lang.Integer affirmationCount;
	@org.kie.api.definition.type.Label(value = "Sequence")
	private java.lang.Integer sequence;

	@org.kie.api.definition.type.Label(value = "User Group")
	private java.lang.String userGroupName;

	public CIBGroupInfo() {
	}

	public java.lang.Integer getAffirmationCount() {
		return this.affirmationCount;
	}

	public void setAffirmationCount(java.lang.Integer affirmationCount) {
		this.affirmationCount = affirmationCount;
	}

	public String toString() {
		return "affirmationCount: " + affirmationCount + " seqence: " + sequence +"userGroupName: " +userGroupName;
	}

	public java.lang.Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(java.lang.Integer sequence) {
		this.sequence = sequence;
	}

	public java.lang.String getUserGroupName() {
		return this.userGroupName;
	}

	public void setUserGroupName(java.lang.String userGroupName) {
		this.userGroupName = userGroupName;
	}

	public CIBGroupInfo(java.lang.Integer affirmationCount,
			java.lang.Integer sequence, java.lang.String userGroupName) {
		this.affirmationCount = affirmationCount;
		this.sequence = sequence;
		this.userGroupName = userGroupName;
	}

}