package com.myspace.cib_phase2;

import com.myspace.cib_phase2.modal.Transaction;
import com.myspace.cib_phase2.modal.CIBGroupInfo;


//from row number: 1
//10000 - 20000
rule "Row 1 GetListOfUserGroup"
	ruleflow-group "user-group"
	dialect "mvel"
	when
		f1 : Transaction( amount > 10000, amount < 20000 )
	then
	
	System.out.println("Group1")
    CIBGroupInfo info1 = new CIBGroupInfo( );
	info1.setUserGroupName("approval-g1");
	f1.addUsergroups( info1 );
	insert(f1);
end

rule "Row 2 GetListOfUserGroup"
	ruleflow-group "user-group"
	dialect "mvel"
	when
		f1 : Transaction( amount > 19999 )
	then
	
	System.out.println("Group2")
    CIBGroupInfo info1 = new CIBGroupInfo( );
	info1.setUserGroupName("approval-g2");
	f1.addUsergroups( info1 );
	insert(f1);
end

rule "Row 3 GetListOfUserGroup"
	ruleflow-group "user-group"
	dialect "mvel"
	when
		f1 : Transaction( amount > 0 )
	then
	
	System.out.println("Group3")
    CIBGroupInfo info1 = new CIBGroupInfo( );
	info1.setUserGroupName("approval-g3");
	f1.addUsergroups( info1 );
	insert(f1);
end
