template header
condLessThan
condGreaterThan
actSalary

package org.drools.examples.templates;

import com.cis.drool_rest.models.Customer;

template "loans"

rule "Set max amount from identifier @{row.rowNumber}"
no-loop
when
	cc: Customer(experience > @{condLessThan}, experience < @{condGreaterThan} )
then
	System.out.println("group.... @{row.rowNumber}");
	modify (cc) {
		setSalary(@{actSalary})
	}
end

end template